### ISSUE TITLE
API to work on buffers directly

### ISSUE THREAD

**Issue by c-cube** [xavierleroy/camlzip#26]
sometimes one needs to compress/decompress data that doesn't come directly from an `{in,out}_channel` (as part of a bigger pipeline). Right now I can't find a way of doing that.

**Comment by alainfrisch** [comment]
The `Zlib` module already allows working on buffer or other streams directly, but indeed, it would be useful to have the same available for `Gzip`.  We are internally using the patch from #27, which is a step into this direction (for decompressing only, and when the full data is available in a `bytes` buffer).

**Comment by c-cube** [comment]
@alainfrisch indeed, but the docs are somewhat, hum, lacking. I'd appreciate something that looks like the usual buffered functions, or a code example :-)

**Comment by c-cube** [comment]
ok, works for me for `Zlib`. I opened another issue for the docs.
