### ISSUE TITLE
OPAM Package

### ISSUE THREAD

**Issue by demurgos** [xavierleroy/camlzip#3]
Hi,
Your library seems to be a good wrapper for zlib and it might be interesting to use it for [Haxe](https://github.com/HaxeFoundation/haxe). The next version of Haxe is planned to integrate with OCaml's package manager: [OPAM](https://opam.ocaml.org/).

What is the current state of this library relative to OPAM ? It seems that [camlzip](https://opam.ocaml.org/packages/camlzip/) is on OPAM, but it was published by a third-party author. Do you know him, is it a reliable source ? It would be better if you were the person who published the package since it seems that this is the home of the project.

**Comment by xavierleroy** [comment]
Being somewhat busy, I'm very happy that others are volunteering to OPAM-package my libraries.  If you have a problem with that, it's your problem.

**Comment by demurgos** [comment]
OK, thank you for you answer.

This was mostly a trust issue, but if you acknowledge it as a valid source it is fine. It might be good to mention the OPAM package in the README.md then.
