### ISSUE TITLE
The library can leak

### ISSUE THREAD

**Issue by dbuenzli** [xavierleroy/camlzip#41]
It's not entirely evident from the zlib docs but once you have called the `{inflate,deflate}Init` function you need to have a call to `{inflate,deflate}End` otherwise you will leak internally allocated structures. 

As such the finalizer [here](https://github.com/xavierleroy/camlzip/blob/3b0e0a5f774a86882bb45235140d550d2b5b481f/zlibstubs.c#L55-L63) should be adapted (perhaps easiest is to have a different finalizer for inflate and deflate initialized streams).

The following loops can be used to exhibit the behaviour: 

```ocaml
let rec loop_leak () = ignore (Zlib.inflate_init false); loop_leak ()

let rec loop_noleak () =
  let s = Zlib.inflate_init false in
  Zlib.inflate_end s; loop_noleak ()

let () = loop_leak ()
```

**Comment by xavierleroy** [comment]
Well spotted.  Proposed fix at #42 .
