### ISSUE TITLE
Retrieve an entry's compression level when `compression_method` is the deflate algorithm.

### ISSUE THREAD

**Issue by zoj613** [xavierleroy/camlzip#49]
As the title says, is there a way to get an entry's compression level? I feel this feature is pretty useful if one wants to keep the entry data "intact" when say, moving it to another zip archive. Looking at the `compression_method` type definition, wouldn't something like
```ocaml
type compression_level = Stored | Deflated of int
```
make sense?

The reason why I'm requesting this feature is that I have a workflow where I try to erase a zip entry by 
1) iterating over the entries of a zip while filtering out the unwanted entry.
2) truncate the current zip's path.
3) add the desired entries less the deleted one to the truncated zip.
This seems necessary since the only way the API allows one to add a zip entry to a zip file is by using its actual uncompressed bytes (meaning I can't use a give `Zip.entry` type variable and add it to a given zip directly. This means that when decompressing the entry we lose information about the compression level that used to add it to its original zip file.

Here is how i've implemented this workflow:
```ocaml
let with_open_in path f =
  let ic = Zip.open_in path in
  Fun.protect ~finally:(fun () -> Zip.close_in ic) @@ fun () -> f ic

let with_open_out path f =
  let oc = Zip.open_update path in
  Fun.protect ~finally:(fun () -> Zip.close_out oc) @@ fun () -> f oc

let add_to_zip ~oc ~level (path, v) = Zip.add_entry ?level v oc path

let delete zippath level key =
  let path_value_pair ~ic acc = function
    | (e : Zip.entry) when e.filename = key -> acc
    | e -> (e.filename, Zip.read_entry ic e) :: acc
  in
  let filter_entries ic = List.fold_left (path_value_pair ~ic) [] (Zip.entries ic) in
  let pairs = with_open_in zippath filter_entries in
  let oc = Zip.open_out zippath in Zip.close_out oc;  (* truncate the old zip file *)
  with_open_out zippath @@ fun oc -> List.iter (add_to_zip ~oc ~level) pairs

```

Notice that in the `delete` function, I am forced to use a custom `level` to re-add the original zip entries back to the file. It seems like being able to re-use the old level is necessary to preserve an entry's properties. Or maybe it would be better to allow adding an entry to a zip archive using type `Zip.entry` instead of `string`? What do you think?

**Comment by xavierleroy** [comment]
I don't know of any way to determine the compression level that was used for an entry in a ZIP file.  This info is not stored anywhere in the ZIP file metadata, just whether compression was used.  https://stackoverflow.com/questions/40082645/how-to-find-the-compression-level-of-a-zip-file suggests re-compressing the data with various levels until the size matches that of the initial compressed entry, but that's ugly.

I'm not sure what you're trying to achieve, but let me mention two possibly-relevant points:
- The CamlZip API currently does not export a "remove an entry from a ZIP file opened for writing" operation.  It would be easy to implement such an operation that just removes the entry from the catalog of entries (the one that is written when the ZIP file handler is closed), thus making it invisible.  But the actual data would remain in the ZIP file, which is not great.
- Another possible extension of the API would be a function that copies an entry from a ZIP file opened for reading to a ZIP file opened for writing, without decompressing and recompressing.  I don't see any technical difficulty here, it's just that it feels like an unusual need.

**Comment by zoj613** [comment]
What I really want to do is be able to use camlzip to rename or delete zip entries from an opened archive. The only way I have managed to make this work is using the code snippet from my previous comment. However because there is no way to get information about the compression level used to compressed an entry's bytes, then I guess my current approach is good enough. I will probably have to add documentation to indicate that the existing zip archive entries will be re-compressed using a new level upon entry rename or deletion.
